version: '3.5'

# Define services
#
services:
    web:
        image: nginx:1.15
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/project/
        depends_on:
            - fpm
        ports:
            - "80:80"

    fpm:
        image: jeckel/php-test:7.3-fpm-alpine
        volumes:
            - ./:/var/www/project/
        working_dir: /var/www/project/

    selenium:
        build:
            context: docker/selenium
            shm_size: 2gb
##        image: selenium/standalone-chrome:latest
#        image: selenium/standalone-firefox:latest
#        volumes:
#          - /dev/shm:/dev/shm
        depends_on:
          - web

    codeception:
        image: jeckel/php-test:7.3-cli-alpine
        environment:
            SELENIUM_HOST: "selenium:4444"
        volumes:
            - ./:/var/www/project/
        working_dir: /var/www/project/
        depends_on:
            - web
            - selenium
        command: codecept run --coverage --coverage-html
