version: '3.3'

# Define services
#
services:
    web:
        build:
            context: .
            dockerfile: docker/supervisor-nginx-fpm/Dockerfile

    selenium:
        image: selenium/standalone-chrome:latest
        depends_on:
          - web

    codeception:
        build:
            context: .
            dockerfile: docker/circleci-codeception/Dockerfile
        environment:
          SELENIUM_HOST: "selenium:4444"
        depends_on:
          - web
          - selenium
#        command: ./wait-for-it.sh selenium:4444 -- ./vendor/bin/codecept run
