version: '3.3'

networks:
    traefik:
        external:
            name: ${TRAEFIK_NETWORK:-traefik_proxy}

# Define services
#
services:
    web:
        image: nginx:1.15
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/project/
        depends_on:
            - fpm
#        ports:
#            - "80:80"
        labels:
            traefik.port: "80"
            traefik.enable: "true"
            traefik.frontend.rule: "Host:novi.local"
            traefik.docker.network: "${TRAEFIK_NETWORK:-traefik_proxy}"
            traefik.frontend.priority: "1"
        networks:
            default:
            traefik:

    fpm:
#        image: php:7-fpm-alpine
        build:
            context: ./docker/fpm/
        volumes:
            - ./:/var/www/project/
        working_dir: /var/www/project/
        networks:
            default:

    selenium:
        image: selenium/standalone-chrome:latest
        depends_on:
          - web
        networks:
            default:

    codeception:
        image: codeception/codeception
#        build:
#            context: ./docker/codeception
        environment:
            SELENIUM_HOST: "selenium:4444"
        volumes:
            - ./:/var/www/project/
        working_dir: /var/www/project/
        depends_on:
            - web
            - selenium
        command: codecept run --coverage --coverage-html
        networks:
            default:
