version: '3.3'

# Define services
#
services:
    web:
        image: nginx:1.15
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/project/
        depends_on:
            - fpm
        ports:
            - "80:80"

    fpm:
        build:
            context: ./docker/fpm/
        volumes:
            - ./:/var/www/project/
        working_dir: /var/www/project/

    selenium:
        image: selenium/standalone-chrome:latest
        volumes:
          - /dev/shm:/dev/shm
        depends_on:
          - web

    codeception:
        build:
            context: ./docker/codeception
        environment:
            SELENIUM_HOST: "selenium:4444"
        volumes:
            - ./:/var/www/project/
        working_dir: /var/www/project/
        depends_on:
            - web
            - selenium
        command: codecept run --coverage --coverage-html
