version: '3.3'

# Define services
#
services:
    web:
        build:
            context: .
            dockerfile: docker/supervisor-nginx-fpm/Dockerfile
        ports:
            - "80:80"

    selenium:
        image: selenium/standalone-chrome:latest
        depends_on:
          - web

    codeception:
        build:
            contexty: .
            dockerfile: docker/circleci-codeception/Dockerfile
        depends_on:
          - web
          - selenium
        command: ./vendor/bin/codecept run
