version: '3.3'

# Define services
#
services:
    nginx:
        image: nginx:1.15
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/project/
        depends_on:
            - php-fpm
        ports:
            - "80:80"

    php-fpm:
        image: php:7-fpm-alpine
        volumes:
            - ./:/var/www/project/
        working_dir: /var/www/project/
