version: '3.3'

# Define services
#
services:
    nginx:
        image: nginx
        volumes:
            - ./:/var/www/project
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - fpm

    fpm:
        image: php:7-fpm-alpine
        volumes:
            - ./:/var/www/project

    selenium:
        image: selenium/standalone-chrome:latest
        depends_on:
            - nginx

    codeception:
        image: php:7-cli
#        image: php:7-cli-alpine
        environment:
            SELENIUM_HOST: "selenium:4444"
        volumes:
            - ./:/var/www/project
        working_dir: /var/www/project
        depends_on:
            - nginx
            - selenium
        command: ./docker/wait-for-it.sh selenium:4444 -- php ./vendor/bin/codecept run
#        command: php ./vendor/bin/codecept run --coverage --coverage-html
