version: '3.3'

# Define services
#
services:
    nginx:
        image: nginx
        volumes:
            - ./:/var/www/project
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - fpm

    fpm:
        image: php:7-fpm-alpine
        volumes:
            - ./:/var/www/project

    selenium:
        image: selenium/standalone-chrome:latest
        depends_on:
            - nginx

    codeception:
        build:
            context: .
            dockerfile: docker/circleci-codeception/Dockerfile
        environment:
            SELENIUM_HOST: "selenium:4444"
        depends_on:
            - nginx
            - selenium
        command: run --coverage --coverage-html
