# .circleci/config.yml
# Configure Jobs:
version: 2
jobs:
    # Will build the source code with deps and store in cache to be reused in next steps
    composer:
        docker:
            - image: composer
        steps:
            - checkout
            - restore_cache:
                  name: Restore composer's vendor cache
                  keys:
                      - vendor-v1-{{ checksum "composer.lock" }}
            - run:
                  name: Install composer deps
                  command: composer install && chmod -R 777 vendor
            - save_cache:
                  name: Save composer's vendor in cache
                  key: vendor-v1-{{ checksum "composer.lock" }}
                  paths:
                      - "vendor"
            - save_cache:
                  name: Save builded source in cache
                  key: source-v1-{{ .Environment.CIRCLE_SHA1 }}
                  paths: .

    build:
        machine:
            docker_layer_caching: true

        working_directory: ~/repo

        steps:
            - restore_cache:
                  name: Restore composer's vendor cache
                  keys:
                      - source-v1-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                  name: Install Docker Compose
                  command: |
                      curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                      chmod +x ~/docker-compose
                      mv ~/docker-compose /usr/local/bin/docker-compose

            - run: docker-compose -f docker-compose.circleci.yml up -d web selenium

            - run:
                name: Check docker socket
                command: docker ps

            - run: sleep 5

            - run: docker-compose -f docker-compose.circleci.yml up
#
#            - run: docker build -t runner -f docker/supervisor-nginx-fpm/Dockerfile .
#            - run: docker run -d runner
#
#            - run:
#                  name: Check docker socket
#                  command: docker ps

# Define the workflow
workflows:
    version: 2
    # Always run code-quality
    build:
        jobs:
            - composer
            - build:
                  requires:
                      - composer
