# .circleci/config.yml
# Configure Jobs:
version: 2.1
orbs:
    codecov: codecov/codecov@1.0.4
jobs:
    build:
        machine:
            docker_layer_caching: true
        steps:
            - checkout
            - run:
                  name: Install Docker Compose
                  command: |
                      curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                      chmod +x ~/docker-compose
                      sudo mv ~/docker-compose /usr/local/bin/docker-compose
            - run:
                  name: Pull images
                  command: |
                      docker-compose pull

            - restore_cache:
                  name: Restore composer's vendor cache
                  keys:
                      - vendor-v1-{{ checksum "composer.lock" }}
            - run:
                  name: Install composer deps
                  command: docker-compose run --rm codeception composer install
            - save_cache:
                  name: Save composer's vendor in cache
                  key: vendor-v1-{{ checksum "composer.lock" }}
                  paths:
                      - "vendor"

            - run:
                  name: Launch services
                  command: docker-compose up -d web fpm selenium
            - run:
                  name: Run codeception
                  command: docker-compose run --rm codeception wait-for.sh selenium:4444 -- ./vendor/bin/codecept run --coverage --coverage-html --coverage-xml

            - run:
                  name: coveralls
                  command: |
                      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
                      chmod +x php-coveralls.phar
                      ./php-coveralls.phar --verbose --config .coveralls.yml

            - codecov/upload:
                  file: tests/_output/coverage.xml

            - store_artifacts:
                  path: tests/_output
