# .circleci/config.yml
# Configure Jobs:
version: 2
jobs:
    # Will build the source code with deps and store in cache to be reused in next steps
    composer:
        docker:
            - image: composer
        working_directory: /tmp/project
        steps:
            - checkout
            - restore_cache:
                  name: Restore composer's vendor cache
                  keys:
                      - vendor-v2-{{ checksum "composer.lock" }}
            - run:
                  name: Install composer deps
                  command: |
                       composer install
            - save_cache:
                  name: Save composer's vendor in cache
                  key: vendor-v2-{{ checksum "composer.lock" }}
                  paths:
                      - "vendor"
            - save_cache:
                  name: Save builded source in cache
                  key: source-v2-{{ .Environment.CIRCLE_SHA1 }}
                  paths: .

    build:
        machine:
            docker_layer_caching: true

#        working_directory: ~/project
        working_directory: /tmp/project

        steps:
            - restore_cache:
                  name: Restore composer's vendor cache
                  keys:
                      - source-v2-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                  name: Fix permissions
                  command: sudo chown -R $(id -u):$(id -g) .

#            - run: mv /tmp/project ~/
#            - run:
#                  name: Install Docker Compose
#                  command: |
#                      curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#                      chmod +x ~/docker-compose
#                      mv ~/docker-compose /usr/local/bin/docker-compose

            - run:
                name: Build images
                command: docker-compose build

            - run:
                name: Launch services
                command: docker-compose up -d web fpm selenium

            - run: docker-compose run codeception
            - store_artifacts:
                  path: /tmp/project/tests/_output
#                  path: ~/project/tests/_output

# Define the workflow
workflows:
    version: 2
    # Always run code-quality
    build:
        jobs:
            - composer
            - build:
                  requires:
                      - composer
