# .circleci/config.yml
# Configure Jobs:
version: 2
jobs:

    build:
        docker:
            - image: docker:git
            - image: selenium/standalone-chrome:latest

        working_directory: ~/repo

        steps:
            - checkout

            - setup_remote_docker
            - run:
                name: Check docker socket
                command: docker ps

            - run: docker build -t runner -f docker/supervisor-nginx-fpm/Dockerfile .

            - run:
                  name: Check docker socket
                  command: docker ps

